apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      restartPolicy: Always
      containers:
      - name: my-container-1
        image: localhost:5000/examplekubernetesapplication:0.2
        env:
        - name: URL
          value: "https://cloudflare.com"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      - name: my-container-2
        image: localhost:5000/examplekubernetesapplication:0.2
        env:
        - name: URL
          value: "https://google.com"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      - name: my-container-3
        image: localhost:5000/examplekubernetesapplication:0.2
        env:
        - name: URL
          value: "https://bing.com"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"